#!/bin/sh -e
#
# $Id: unpatch-source,v 1.2 2003/06/18 18:12:05 peloy Exp $
#

# We want to reverse the patches in the opposite order we applied
#	them, hence the 'ls|sort -r'.
for patch in `ls debian/patches/*.patch | sort -r`; do
	patch -p1 -R < $patch
done

exit 0
